apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: station-backend
spec:
  ingressClassName: nginx
  rules:
    - host: api.station.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: station-backend
                port:
                  number: 3001
