apiVersion: v1
kind: Service
metadata:
  name: station-backend
  labels:
    app: station-backend
spec:
  type: {{ .Values.service.type }}
  selector:
    app: station-backend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3001
